### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by drewsed** [daddycocoaman/BeaconGraph#5]
Hi,

nice work and thanks for sharing. 
I have a problem, when I start the docker containers on a fresh MXLinux VM everything fires up and I can login. But when I load the ``mesh.csv`` I get the following error in the terminal:
```beacongraph-backend_1   | 2020-12-03 20:38:58.831 | INFO     | uvicorn.protocols.http.httptools_impl:send:452 - 172.18.0.1:57622 - "OPTIONS /api/upload HTTP/1.1" 200
beacongraph-backend_1   | 2020-12-03 20:38:58.840 | INFO     | uvicorn.protocols.http.httptools_impl:send:452 - 172.18.0.1:57622 - "POST /api/upload HTTP/1.1" 200
beacongraph-backend_1   | 2020-12-03 20:38:58.840 | INFO     | backend.db:__init__:29 - Connecting to bolt://beacongraph-neo4j:7687
beacongraph-backend_1   | 2020-12-03 20:39:00.046 | ERROR    | backend.parser:parseUpload:214 - Not an Airodump file!
beacongraph-backend_1   | 2020-12-03 20:39:00.205 | INFO     | backend.parser:process:229 - Completed ingestion of mesh.csv
```
Also no results are found on all example queries.

Any ideas?

Thanks

**Comment by daddycocoaman** [comment]
That is very weird...I haven't seen that happen before, since the screenshot in the README contains nodes from that csv.  The logic to determine if it's an Airodump file is pretty loose:

`if content.startswith(b"\r\nBSSID, First time seen, Last time seen, channel"):`

And it looks like the file may not be meeting this criteria. Honestly, I wanted to replace the server-side logic with a simple ability for the user to decide which type of file they're uploading (as more formats become available in the future) but I couldn't get it done in time before pushing this new version.

But for your current issue, I wonder if there's some text encoding difference that happens between Windows/Linux (I dev on Windows). I'll test this out in a different environment and get back to you.

**Comment by drewsed** [comment]
Hi thanks for your answer.

I created my own ``airodump-output.csv`` file with airodump-ng and when I compare it with your file in Notepad++ with enabled ``Show Line Endings`` it differs:

``mesh.csv`` starts with ``LF``
``airodump-output.csv`` starts with ``CR`` ``LF``

Also this file parses fine and I can visualize the content as expected. So this seems a portability issue, and it seems python is handling the different line endings correctly.

I leave this issue open as a reminder, but feel free to close it 😃

**Comment by daddycocoaman** [comment]
Ok, cool. Figured that's what it was. Made a change to address this. Thanks for the report!
